### ISSUE TITLE
Difficulty in Configuring Firewall Rules for VPS on GCP

### ISSUE THREAD

**Issue by kv-chiu** [Toothbrush-Lee/Free-IPv6#1]
**Body:**

Hello,

I have been using the GCP-based solution, which generally offers excellent capabilities. However, I've encountered a specific issue that may confuse beginners, especially regarding the configuration of firewall rules.

After installing x-ui, if the firewall rules are not configured correctly, access to the web-UI interface is blocked. This could be a significant barrier for those new to GCP or unfamiliar with network management.

**Issues Faced:**

- Although GCP already provides documentation for configuring firewall rules, the tutorials do not sufficiently highlight this point.
  - https://cloud.google.com/firewall/docs/firewalls
  - https://cloud.google.com/firewall/docs/using-firewalls#rules-for-common-use-cases

**Request:**

Could we enhance the documentation or tutorials to include:

- Explicitly emphasize the GCP-provided documentation on firewall rule configuration in the tutorials so that users can more easily find and utilize these resources.

Such improvements could greatly assist beginners in effectively using the platform without facing initial roadblocks.

Thank you for considering this enhancement.

**Comment by kv-chiu** [comment]
fix: https://github.com/Toothbrush-Lee/Free-IPv6/pull/2

**Comment by Toothbrush-Lee** [comment]
Thank you so much for contribution!
